# Purpose of this file is to build, test, and deploy the backend
# currently zips backend into a release.zip and give it to Azure to deploy
# reports errors on GitHub Actions tab
# assumes you have code to be deployed
# important to be valid in order to actually deploy the web app
# tests should be valid otherwise code will deploy even if code is broken
name: Build and deploy Node.js app to Azure Web App - SIDER

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    # env from tests left over, not needed for azure connection
    #env:
    #  MONGODB_URI: ${{ secrets.MONGODB_URI }}
    #  TOKEN_SECRET: ${{ secrets.TOKEN_SECRET }}
    #  NODE_ENV: test
    #  PORT: 8000
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install backend deps
        working-directory: packages/express-backend
        run: npm ci --omit=dev --workspaces=false
      # omit dev dependencies, working in directory already
      - name: Build backend
        run: npm run -w express-backend build --if-present

      - name: Test backend
        run: npm run -w express-backend test --if-present

      - name: Create deployment zip
        run: |
          cd packages/express-backend
          zip -r ../../release.zip ./*
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  # note this only runs if build is successful
  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: read
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: node-app
          path: .

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: SIDER
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: release.zip
          # omit slot-name unless you're deploying to a non-production slot
